name: metamask-monad-delegation
description: Index mUSDC transfers and delegation events on Monad testnet
ecosystem: evm
schema: schema.graphql

networks:
  - id: 10143
    start_block: 0
    rpc_config:
      url: https://rpc.ankr.com/monad_testnet
    contracts:
      - name: MonUSDC
        abi_file_path: ./abis/MonUSDC.json
        handler: src/EventHandlers.ts
        address:
          - 0x3A13C20987Ac0e6840d9CB6e917085F72D17E698
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 value)

      - name: DelegationManager
        abi_file_path: ./abis/DelegationManager.json
        handler: src/EventHandlers.ts
        address:
          - 0xdb9B1e94B5b69Df7e401DDbedE43491141047dB3
        events:
          - event: EnabledDelegation(bytes32 indexed delegationHash, address indexed delegator, address indexed delegate, tuple delegation)
          - event: RedeemedDelegation(address indexed rootDelegator, address indexed redeemer, tuple delegation)
          - event: DisabledDelegation(bytes32 indexed delegationHash, address indexed delegator, address indexed delegate, tuple delegation)

